import {pageUrl,apiFetch} from '@/lib/urls';
'use client';
import {useCallback,useEffect,useState} from 'react';
import plan from './plan.json';
import StudyTimer from './study-timer';
import {durationText,type TimerState} from './study-timer-model';
import SiteNav from './site-nav';
import SiteHeader from './site-header';
import SiteFooter from './site-footer';
import PlanGuide from './plan-guide';
import {books,timeline} from './plan-content';
import {Progress} from '@/components/ui/progress';
import {Tabs,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Button} from '@/components/ui/button';
import {BookOpen,Clock3,Check,RefreshCw,CalendarDays,CheckCircle2,AlertCircle} from 'lucide-react';
import {Toaster,toast} from 'sonner';
type Day=typeof plan[number]['days'][number];
type StudyRecord={date:string;status:string;deferredTo:string;version:number;updatedAt:string};
type Space={records:StudyRecord[]};
const allDays=plan.flatMap(w=>w.days),studyDays=allDays.filter(d=>d.kind==='study');
const labels:Record<string,string>={todo:'未开始',doing:'进行中',done:'已完成',deferred:'已顺延'};
function chinaDate(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());return ['year','month','day'].map(k=>p.find(x=>x.type===k)?.value).join('-')}
function short(s:string){return s.slice(5).replace('-','.')}
function initialWeek(day:string){const index=plan.findIndex(w=>day<=w.days[w.days.length-1].date);return index<0?plan.length-1:index}
export default function Dashboard({initialTab='plan'}:{initialTab?:string}){
const [today,setToday]=useState(chinaDate),[week,setWeek]=useState(0),[tab,setTab]=useState(initialTab),[space,setSpace]=useState<Space|null>(null),[connecting,setConnecting]=useState(true),[connectionError,setConnectionError]=useState(''),[selected,setSelected]=useState<Day|null>(null),[draft,setDraft]=useState({status:'todo',deferredTo:'',version:0}),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState(''),[filter,setFilter]=useState('all'),[lastSync,setLastSync]=useState('');
const [timerState,setTimerState]=useState<TimerState|null>(null),[timerDate,setTimerDate]=useState<string|null>(null);
const timerChanged=useCallback((s:TimerState)=>setTimerState(s),[]);
useEffect(()=>setTab(initialTab),[initialTab]);
const refresh=useCallback(async(silent=false)=>{if(!silent)setConnecting(true);try{const r=await apiFetch('/api/space',{cache:'no-store'});const data=await r.json() as Space & {error?:string};if(!r.ok)throw new Error(data.error||'同步失败，请重试。');setSpace(data);setConnectionError('');setLastSync(new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Shanghai'}));}catch(e){setConnectionError((e as Error).message)}finally{setConnecting(false)}},[]);
useEffect(()=>{const d=chinaDate();setToday(d);setWeek(initialWeek(d));const params=new URLSearchParams(location.search);const w=Number(params.get('week'));if(Number.isInteger(w)&&w>=1&&w<=11)setWeek(w-1);const t=params.get('tab');if(['overview','books','timeline'].includes(t||''))setTab(t!);if(location.hash.startsWith('#s='))history.replaceState(null,'',location.pathname+location.search);void refresh();const timer=window.setInterval(()=>{setToday(chinaDate());if(document.visibilityState==='visible')void refresh(true)},30000);const focus=()=>void refresh(true);window.addEventListener('focus',focus);return()=>{clearInterval(timer);window.removeEventListener('focus',focus)}},[refresh]);
const recordMap=Object.fromEntries((space?.records??[]).map(r=>[r.date,r]));
const effectiveMap={...recordMap};
for(const date of new Set([...(timerState?.sessions.filter(s=>!s.deleted).map(s=>s.date)||[]),...(timerState?.active?[timerState.active.date]:[])])){if(!effectiveMap[date]||effectiveMap[date].status==='todo')effectiveMap[date]={date,status:'doing',deferredTo:'',version:recordMap[date]?.version||0,updatedAt:''}}

const current=plan[week],completed=studyDays.filter(d=>recordMap[d.date]?.status==='done'),weekStudy=current.days.filter(d=>d.kind==='study'),weekDone=weekStudy.filter(d=>recordMap[d.date]?.status==='done');
const overdue=studyDays.filter(d=>{const r=recordMap[d.date];return r?.status!=='done'&&(r?.deferredTo||d.date)<today});
const deferred=studyDays.filter(d=>recordMap[d.date]?.status==='deferred');
const daysToExam=Math.ceil((Date.parse('2026-12-19T00:00:00Z')-Date.parse(today+'T00:00:00Z'))/86400000);
const writable=!!space;
function openDay(d:Day,adjust=false){if(d.kind==='study'&&!adjust){setTimerDate(d.date);return;}const r=recordMap[d.date];setDraft({status:r?.status??'todo',deferredTo:r?.deferredTo??'',version:r?.version??0});setSelected(d);setSaveError('')}
async function save(){if(!selected||!writable)return;setSaving(true);setSaveError('');try{const r=await apiFetch('/api/record',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({date:selected.date,...draft})});const data=await r.json() as {record:StudyRecord;error?:string};if(!r.ok){if(r.status===409)void refresh(true);throw new Error(data.error||'保存失败，请重试。')}setSpace(s=>s?{...s,records:[...s.records.filter(x=>x.date!==selected.date),data.record]}:s);setSelected(null);toast.success('学习进度已保存并同步。')}catch(e){setSaveError((e as Error).message)}finally{setSaving(false)}}
useEffect(()=>{const ctx=(document as Document&{modelContext?:{registerTool:(t:unknown,o:unknown)=>unknown}}).modelContext;if(!ctx)return;const lifecycle=new AbortController();try{Promise.resolve(ctx.registerTool({name:'view_study_week',title:'查看每周学习计划',description:'切换到指定周，查看每日任务和已加载的共享学习记录。',inputSchema:{type:'object',properties:{week:{type:'integer',minimum:1,maximum:11}},required:['week'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{const n=(input as {week?:number})?.week;if(!Number.isInteger(n)||n!<1||n!>11)throw new Error('week 必须为1至11的整数');setWeek(n!-1);setTab('plan');return {week:n,goal:plan[n!-1].goal,days:plan[n!-1].days}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
function status(d:Day){if(d.kind==='exam')return '初试';if(d.kind==='rest')return '休息';if(d.kind==='buffer')return '休息 / 补缺';if(!space)return '同步中';const r=effectiveMap[d.date];if(r?.status==='done')return '已完成';if(r?.status==='doing')return '进行中';if(space&&(r?.deferredTo||d.date)<today)return '待补';return labels[r?.status??'todo']}
const visibleDays=current.days.filter(d=>filter==='all'||(d.kind==='study'&&recordMap[d.date]?.status!=='done'));
return <main className="shell"><Toaster position="top-center" richColors/><SiteHeader status={connectionError?'同步未完成':connecting?'正在同步':space?'已同步 '+lastSync:'待同步'}/>
<SiteNav active={tab==='overview'?'/progress':'/'+tab}/>{import.meta.env.VITE_DATA_PROVIDER==='preview'&&<div className="error-banner">独立测试版 · 打卡仅保存在当前浏览器，不会影响正式学习记录</div>}{(tab==='plan'||tab==='overview')&&<StudyTimer onChange={timerChanged} requestedDate={timerDate} onSaved={()=>refresh(true)} onClose={()=>setTimerDate(null)} onOpen={setTimerDate} completedDates={completed.map(d=>d.date)} onAdjust={date=>{setTimerDate(null);const d=studyDays.find(d=>d.date===date);if(d)openDay(d,true)}}/>}<Tabs value={tab} onValueChange={setTab}>
{connectionError&&<div className="error-banner" role="alert"><AlertCircle size={17}/><span>{connectionError}</span><button onClick={()=>refresh()}>重新同步</button></div>}
<TabsContent value="plan"><div className="workspace"><aside className="week-rail" aria-label="选择学习周"><p className="eyebrow">11 周备考日历</p>{plan.map((x,i)=>{const done=x.days.filter(d=>d.kind==='study'&&recordMap[d.date]?.status==='done').length;return <button key={i} aria-pressed={week===i} className={'week-button '+(week===i?'active':'')} onClick={()=>{setWeek(i);setFilter('all')}}><span className="week-num">{String(i+1).padStart(2,'0')}</span><span>第 {i+1} 周<small>{short(x.days[0].date)} – {short(x.days[x.days.length-1].date)}</small></span><span className="week-phase">{done?done+'天':x.phase}</span></button>})}<div className="rail-footer"><b>199 管综 · 204 英语（二）</b><p>10月基础 · 11月真题<br/>12月套卷与冲刺</p></div></aside>
<section className="main-area"><div className="title-line"><div><p className="eyebrow">2026.10.08 — 12.19</p><h1>学习计划</h1><p className="page-subtitle">每日任务与学习记录同步，按实际休息日调整。</p></div><div className="countdown"><strong>{Math.max(0,daysToExam)}</strong><span>{daysToExam<0?'初试已结束':daysToExam===0?'今天初试':'天后初试'}</span></div></div>
<div className="stats"><article><span>本周完成</span><strong>{weekDone.length} <small>/ {weekStudy.length} 天</small></strong><Progress aria-label="本周完成率" value={weekStudy.length?weekDone.length/weekStudy.length*100:0}/></article><article><span>总进度</span><strong>{Math.round(completed.length/studyDays.length*100)} <small>%</small></strong><p>已完成 {completed.length} / {studyDays.length} 天</p></article><article><span>需要跟进</span><strong>{space?overdue.length:'—'} <small>项待补</small></strong><p>顺延按新日期判断</p></article></div>
<PlanGuide/><div className="section-head week-heading"><div><p className="eyebrow">WEEK {String(current.week).padStart(2,'0')} · {current.phase}阶段</p><h2>{current.goal}</h2></div><button className="text-button" onClick={()=>{setWeek(initialWeek(today));setFilter('all')}}>回到本周</button></div>
<div className="list-toolbar"><p>本周必做 {weekStudy.length} 天 · {current.days.reduce((n,d)=>n+d.minutes,0)/60} 小时；周五不计入完成率。</p><button className={'filter-button '+(filter==='pending'?'on':'')} aria-pressed={filter==='pending'} onClick={()=>setFilter(filter==='all'?'pending':'all')}>只看未完成</button></div>
<div className="day-list">{visibleDays.map(d=><button className={'day-card '+(d.date===today?'today ':'')+(recordMap[d.date]?.status==='done'?'complete':'')} key={d.date} onClick={()=>openDay(d)}><span className="day-stamp"><b>{d.day}</b><small>{short(d.date)}</small>{d.date===today&&<em>今天</em>}</span><span className="day-info"><span className={'subject '+(d.subject==='英语'?'english':'')}>{d.kind==='study'?d.subject:d.kind==='exam'?'考试':d.kind==='buffer'?'休息 / 补缺':'休息'}</span><span className="task-text">{d.task}</span><small><Clock3 size={14}/>{d.kind==='study'?`${d.day==='周六'||d.day==='周日'?'休息日':'晚间'} · 计划 ${d.minutes} 分钟`:d.kind==='exam'?'上午管综 · 下午英语':d.kind==='buffer'?'不设新任务 · 补缺在原任务记录':'调整休息'}{recordMap[d.date]?.deferredTo&&' · 顺延至 '+short(recordMap[d.date].deferredTo)}</small></span><span className={'task-state '+(effectiveMap[d.date]?.status??'')}>{recordMap[d.date]?.status==='done'&&<Check size={13}/>} {status(d)}{d.kind==='study'&&(recordMap[d.date]?.status!=='done'||timerState?.sessions.some(s=>!s.deleted&&s.date===d.date))&&<small className="card-study-time">{timerState?.sessions.some(s=>!s.deleted&&s.date===d.date)?<>累计 {durationText(timerState.sessions.filter(s=>!s.deleted&&s.date===d.date).reduce((n,s)=>n+s.durationMs,0))}<br/>{timerState.sessions.filter(s=>!s.deleted&&s.date===d.date).length} 次打卡</>:recordMap[d.date]?.status==='done'?'未记录时长':'点击学习打卡'}</small>}</span></button>)}{visibleDays.length===0&&<div className="empty-state"><CheckCircle2/><h2>本周任务已全部完成</h2><p>可以回顾错题，也给自己留一点休息时间。</p></div>}</div>
</section></div></TabsContent>
<TabsContent value="overview"><section className="wide-content"><div className="section-heading"><div><p className="eyebrow">学习记录同步</p><h1>学习进度</h1><p className="muted">所有人查看和更新同一份进度，无需登录。</p></div><button className="outline-button" onClick={()=>refresh()} disabled={connecting}><RefreshCw size={16}/>同步进度</button></div><div className="stats overview-stats"><article><span>累计完成</span><strong>{completed.length}<small> / {studyDays.length} 天</small></strong><Progress value={completed.length/studyDays.length*100}/></article><article><span>总进度</span><strong>{Math.round(completed.length/studyDays.length*100)}<small> %</small></strong><p>按完成的学习日计算</p></article><article><span>待补 / 已顺延</span><strong>{space?overdue.length:'—'}<small> / {deferred.length} 项</small></strong><p>顺延后按新日期计算待补</p></article></div><div className="overview-grid"><article className="panel"><h2>每周完成情况</h2><div className="weekly-chart">{plan.map(w=>{const count=w.days.filter(d=>d.kind==='study'&&recordMap[d.date]?.status==='done').length,total=w.days.filter(d=>d.kind==='study').length;return <button key={w.week} className="chart-row" onClick={()=>{setWeek(w.week-1);setTab('plan')}}><span>第{w.week}周</span><Progress value={count/total*100}/><small>{count}/{total}</small></button>})}</div></article><article className="panel"><h2>待补任务 <span className="count-pill">{space?overdue.length:'—'}</span></h2>{!space?<div className="small-empty"><p>{connecting?'正在同步学习记录…':'暂未加载进度，请重新同步。'}</p></div>:overdue.length===0?<div className="small-empty"><CheckCircle2/><p>目前没有逾期未完成的任务。</p></div>:<div className="follow-list">{overdue.map(d=><button key={d.date} onClick={()=>openDay(d)}><b>{short(d.date)} · {d.subject}</b><p>{d.task}</p><small>{recordMap[d.date]?.deferredTo?'已顺延至 '+short(recordMap[d.date].deferredTo):'尚未完成'} · 点击查看</small></button>)}</div>}</article></div></section></TabsContent>
<TabsContent value="books"><section className="wide-content"><div className="section-heading"><div><p className="eyebrow">材料准备</p><h1>书单资料</h1><p className="muted">先用好这5类资料，按多年未系统学习、在职备考选择。基础书兼作习题册，真题承担强化和模拟；这是五类资料，逻辑含两册，英语选两个分册。</p></div><a className="outline-button" href={pageUrl("/plan")}>查看每日计划</a></div><div className="book-grid">{books.map((b,i)=><article className="book-card" key={b.short}><div className="book-number">0{i+1}</div><div><span className="subject">{b.short}</span><h2>{b.name}</h2><p className="muted">{b.edition}</p><p className="book-use">{b.use}</p><p className="book-check">{b.check}</p><small>{/^\d/.test(b.isbn)?'ISBN '+b.isbn:b.isbn}</small><a href={b.url} target="_blank" rel="noreferrer">{b.short==='英语真题'?'查看提高版':'查看版本信息'}</a>{b.extraUrl&&<a href={b.extraUrl} target="_blank" rel="noreferrer">{b.extraLabel}</a>}</div></article>)}</div><p className="book-audit-note">书目核对：2026年10月5日。基础书已对照公开目录，英语分册名称与年份已对照零售书目；管综真题逐年目录尚未取得。推荐基于当前时间与基础假设，并非逐页审校。不同印次的页码、题量可能不同。购书时同时看“2027”、作者、目录和收录年份，ISBN只作辅助识别。</p><div className="tips-grid"><article className="panel"><h2>练习题怎么找</h2><p>基础书按指定小节看例题，再选同考点的基础练习，先独立做再核对；暂不练疑难题。真题按当天列出的年份和卷面题号做，不按书的页码找。</p><p>数学默认“基础考点篇”；逻辑按“基础篇／强化篇”定位。真题按试卷标题年份和卷面题号找。</p></article><article className="panel"><h2>留三套做整卷</h2><p>2024、2025、2026年两科真题留作三轮模拟；基础书中遇到这些年份的题目也跳过。某卷已做过时，用未做过的2022或2023年同科卷替换，记下实际年份。</p><p>另备错题本和空白答题纸；已有大纲词汇书或背词工具选一个沿用。当前不另购数学1000题、逻辑1000题、英语阅读100篇或预测卷。</p></article></div><article className="panel question-map"><h2>题号速查</h2><p><b>管综</b>　1—25 数学 · 26—55 逻辑 · 56 论证有效性分析 · 57 论说文</p><p><b>英语（二）</b>　1—20 完形 · 21—40 阅读Text 1—4 · 41—45 新题型 · 46 翻译 · 47 小作文 · 48 大作文</p></article></section></TabsContent>
<TabsContent value="timeline"><section className="wide-content"><div className="section-heading"><div><p className="eyebrow">2026 报名 · 2027 入学</p><h1>关键时间节点</h1><p className="muted">标注“预计”的时间待当年通知确认。</p></div></div><div className="timeline-layout"><div className="timeline">{timeline.map((t,i)=><article key={t[1]} className={t[3]>=today&&(!i||timeline[i-1][3]<today)?'upcoming':''}><div className="timeline-mark">{String(i+1).padStart(2,'0')}</div><div><p className="eyebrow">{t[0]}</p><h2>{t[1]}</h2><p>{t[2]}</p></div></article>)}</div><aside className="exam-card"><p className="eyebrow">初试两门 · 总分300</p><h2>12月19日</h2><div><b>199 管理类综合能力</b><p>200分 · 3小时</p><small>数学75分 · 逻辑60分<br/>写作65分</small></div><div><b>204 英语（二）</b><p>100分 · 3小时</p><small>完形10分 · 阅读50分<br/>翻译15分 · 写作25分</small></div><a href="https://yz.chsi.com.cn/" target="_blank" rel="noreferrer">研招网官方通知</a><a href="https://yjsy.ncu.edu.cn/info/1171/47816.htm" target="_blank" rel="noreferrer">南昌大学招生简章</a></aside></div></section></TabsContent></Tabs>
<SiteFooter/>
<Dialog open={!!selected} onOpenChange={v=>{if(!saving&&!v)setSelected(null)}}><DialogContent className="study-dialog task-dialog" onInteractOutside={e=>{if(saving)e.preventDefault()}}><DialogTitle>{selected&&short(selected.date)} {selected?.day} · {selected?.subject}</DialogTitle><DialogDescription>{selected?.kind==='study'?`计划 ${selected.minutes} 分钟 · ${selected.day==='周六'||selected.day==='周日'?'实际休息日安排':'下班后完成'}`:'考试与休息安排'}</DialogDescription><div className="full-task">{selected?.task}</div>{selected?.kind==='study'&&<><details className="task-adjustment" open><summary>调整任务状态 / 顺延</summary><label className="form-label">完成状态<Select value={draft.status} disabled={!writable||saving} onValueChange={status=>setDraft(x=>({...x,status}))}><SelectTrigger className="status-select" aria-label="完成状态"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(labels).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select></label>{draft.status==='deferred'&&<label className="form-label">顺延到<input type="date" min={selected.date} max="2026-12-18" value={draft.deferredTo} disabled={!writable||saving} onChange={e=>setDraft(x=>({...x,deferredTo:e.target.value}))}/></label>}{saveError&&<p className="form-error" role="alert">{saveError}</p>}{!space&&<p className="muted small">{connecting?'正在加载进度…':'加载失败，请关闭后点击“重新同步”。'}</p>}<Button className="primary w-full" disabled={saving||!writable} onClick={save}>{saving?'正在保存…':'保存进度'}</Button><p className="muted small">保存后，其他设备打开网页即可看到最新进度。</p></details></>}</DialogContent></Dialog>
</main>}
