import {useCallback,useEffect,useRef,useState} from 'react';
import {Play,Pause,Square,Clock3,Plus,RotateCcw} from 'lucide-react';
import {lookupNetworkRegion} from '@/lib/network-region';
import {apiFetch} from '@/lib/urls';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {chinaDay,durationText,elapsed,type Session,type TimerState} from './study-timer-model';
import plan from './plan.json';
import './study-timer.css';
const days=plan.flatMap(w=>w.days).filter(d=>d.kind==='study');
function deviceLabel(){const ua=navigator.userAgent;const os=/iPhone/.test(ua)?'iPhone · iOS':/iPad/.test(ua)||(/Macintosh/.test(ua)&&navigator.maxTouchPoints>1)?'iPad · iPadOS':/Android/.test(ua)?'Android 手机/平板':/Windows/.test(ua)?'电脑 · Windows':/Macintosh/.test(ua)?'电脑 · macOS':/Linux/.test(ua)?'电脑 · Linux':'未知设备';const browser=/MicroMessenger/.test(ua)?'微信':/Edg/.test(ua)?'Edge':/CriOS|Chrome/.test(ua)?'Chrome':/FxiOS|Firefox/.test(ua)?'Firefox':/Safari/.test(ua)?'Safari':'浏览器';return os+' · '+browser}
const defaultDate=()=>days.find(d=>d.date>=chinaDay())?.date||days[days.length-1].date;
function localTime(s:string){const d=new Date(Date.parse(s)+8*3600000);return d.toISOString().slice(0,19)}
function iso(s:string){return new Date(s+'+08:00').toISOString()}
function niceTime(s:string){return new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}
type Form={version:number;id?:string;date:string;startedAt:string;endedAt:string;minutes:string;note:string};
export default function StudyTimer({onChange,requestedDate,onSaved,onClose,onOpen,onAdjust,completedDates}:{onClose:()=>void;onOpen:(date:string)=>void;onAdjust:(date:string)=>void;completedDates:string[];onChange:(s:TimerState)=>void;requestedDate:string|null;onSaved:()=>Promise<void>}){
 const [state,setState]=useState<TimerState|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now),[date,setDate]=useState(defaultDate),[mode,setMode]=useState<'manual'|'edit'|'save'|null>(null),[form,setForm]=useState<Form|null>(null),[confirm,setConfirm]=useState<'cancel'|string|null>(null),[message,setMessage]=useState(''),[showAll,setShowAll]=useState(false);
 const latestVersion=useRef(-1);
 const accept=useCallback((s:TimerState)=>{if(s.version<latestVersion.current)return;latestVersion.current=s.version;setState(s);onChange(s)},[onChange]);
 const refresh=useCallback(async()=>{try{const r=await apiFetch('/api/timer',{cache:'no-store'}),data=await r.json();if(!r.ok)throw new Error(data.error);accept(data);setError('')}catch(e){setError((e as Error).message)}},[accept]);
 useEffect(()=>{void refresh();const t=setInterval(()=>{if(document.visibilityState==='visible')void refresh()},15000);const f=()=>void refresh();window.addEventListener('focus',f);return()=>{clearInterval(t);window.removeEventListener('focus',f)}},[refresh]);
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(requestedDate)setDate(requestedDate)},[requestedDate]);
 async function act(action:string,extra:Record<string,unknown>={}){if(!state||busy)return false;setBusy(true);setError('');setMessage('');try{const network=action==='start'||action==='manual'?await lookupNetworkRegion():{};const r=await apiFetch('/api/timer',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:state.version,action,device:deviceLabel(),...network,...extra})}),data=await r.json();if(!r.ok){if(r.status===409)void refresh();throw new Error(data.error||'暂未保存，请重试。')}accept(data);return data as TimerState}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 const globalActive=state?.active,active=globalActive?.date===date?globalActive:null,sessions=state?.sessions.filter(s=>!s.deleted)||[],today=chinaDay(new Date(now));
 const weekStart=(()=>{const d=new Date(today+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);return d.toISOString().slice(0,10)})();
 const total=(rows:Session[])=>rows.reduce((n,s)=>n+s.durationMs,0);
 const todayMs=total(sessions.filter(s=>chinaDay(s.startedAt)===today));
 const weekMs=total(sessions.filter(s=>chinaDay(s.startedAt)>=weekStart&&chinaDay(s.startedAt)<=today));
 const taskSessions=sessions.filter(s=>s.date===date);
 const sorted=[...taskSessions].sort((a,b)=>b.startedAt.localeCompare(a.startedAt));
 function edit(row?:Session){setError('');setMode(row?'edit':'manual');const end=new Date().toISOString(),start=new Date(Date.now()-30*60000).toISOString();setForm(row?{version:state!.version,id:row.id,date:row.date,startedAt:localTime(row.startedAt),endedAt:localTime(row.endedAt),minutes:String(Math.round(row.durationMs/60000*1000)/1000),note:row.note}:{version:state!.version,date,startedAt:localTime(start),endedAt:localTime(end),minutes:'30',note:''})}
 function review(session=active,current=state){if(!session?.endedAt||!current)return;setError('');setMode('save');setForm({version:current.version,id:session.id,date:session.date,startedAt:localTime(session.startedAt),endedAt:localTime(session.endedAt),minutes:String(Math.round(Math.floor(session.elapsedMs/1000)/60*1000)/1000),note:''})}
 async function submit(){if(!form||!mode)return;let values;try{values={...form,startedAt:mode==='save'&&active&&form.startedAt===localTime(active.startedAt)?active.startedAt:iso(form.startedAt),endedAt:mode==='save'&&active?.endedAt&&form.endedAt===localTime(active.endedAt)?active.endedAt:iso(form.endedAt),durationMs:Math.round(Number(form.minutes)*60)*1000}}catch{setError('请填写完整的起止时间。');return}if(await act(mode,values)){setMode(null);setForm(null);setMessage(mode==='edit'?'学习记录已保存。':'打卡成功，任务已完成。');if(mode!=='edit')void onSaved()}}

 return <section className="task-timer-shell" aria-label="学习打卡"><div className="study-totals"><span>今日学习 <b>{durationText(todayMs)}</b></span><span>本周学习 <b>{durationText(weekMs)}</b></span><small>已保存的学习时长</small></div>
 {globalActive&&<button className="active-study-bar" onClick={()=>onOpen(globalActive.date)}><span className="active-pulse"/><span>{globalActive.date.slice(5)} · {globalActive.phase==='running'?'正在学习':globalActive.phase==='paused'?'计时已暂停':'打卡待确认'}</span><b>{durationText(elapsed(globalActive,now))}</b><span>查看计时 →</span></button>}
 {!requestedDate&&error&&<p className="clock-error">{error}<button onClick={()=>refresh()}>重新同步</button></p>}
 <Dialog open={!!requestedDate} onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="study-dialog clock-task-dialog"><DialogTitle>{date.slice(5).replace('-','.')} · {days.find(d=>d.date===date)?.subject}</DialogTitle><DialogDescription>{days.find(d=>d.date===date)?.task}</DialogDescription><div className="study-clock task-clock-detail">
 <div className="task-checkin-summary"><span className={completedDates.includes(date)?'task-done-label':''}>{completedDates.includes(date)?'✓ 已完成':'学习记录'}{taskSessions.length>0&&<> · 累计 {durationText(total(taskSessions))} · {taskSessions.length} 次打卡</>}</span><button className="clock-text" onClick={()=>edit()} disabled={!state||busy}><Plus size={16}/>补记</button></div>
 <div className="clock-grid"><div className="clock-focus"><span className="clock-caption">{active?`${active.date.slice(5).replace('-','.')} · ${active.phase==='running'?'专注中':active.phase==='paused'?'已暂停':'待确认打卡'}`:'准备好了，就从现在开始'}</span><div className="clock-digits" aria-label="本次学习时长">{active?durationText(elapsed(active,now)):'00:00:00'}</div>
 <div className="clock-actions">{!active?<button className="clock-primary" disabled={!state||busy||!!globalActive} onClick={()=>act('start',{date})}><Play size={17}/>{taskSessions.length?'再次学习':'开始学习'}</button>:<>{active.phase==='running'?<button disabled={busy} onClick={()=>act('pause')}><Pause size={17}/>暂停</button>:<button disabled={busy} className="clock-primary" onClick={()=>act('resume')}><Play size={17}/>继续计时</button>}{active.phase!=='review'?<button disabled={busy} onClick={async()=>{const result=await act('stop');if(result)review(result.active,result)}}><Square size={15}/>结束计时</button>:<button disabled={busy} onClick={()=>review()}>查看打卡</button>}<button className="clock-text" disabled={busy} onClick={()=>setConfirm('cancel')}>取消本次</button></>}</div>
 {globalActive&&!active&&<p className="clock-notice">{globalActive.date.slice(5)} 的计时尚未结束，请先完成那次打卡。</p>}
 {active&&elapsed(active,now)>4*3600000&&<p className="clock-notice">这次计时已超过4小时。如果忘记结束，请在打卡时修正结束时间与实际学习时长。</p>}
 <p className="clock-privacy">打卡会记录时间、设备和公网 IP，并由 ipwho.is 推测大致地区。{import.meta.env.VITE_DATA_PROVIDER==='preview'&&<small>仅为网络所在地推测，可能有偏差；不获取手机精确定位。</small>}</p><p className="clock-hint">{active?.phase==='review'?'尚未保存。误点结束可继续计时，中间这段时间不计入。':'暂停不计时；关闭网页后仍继续计时。结束后确认保存。'}</p></div>
 </div>
 {error&&<p className="clock-error" role="alert">{error} <button disabled={busy} onClick={()=>refresh()}>重新同步</button></p>}{message&&<p className="clock-success" role="status">{message}</p>}
 <details className="clock-history" open><summary><Clock3 size={16}/>学习记录 <span>{taskSessions.length} 次</span></summary>{!state?<p>正在同步记录…</p>:sorted.length===0?<p className="clock-hint">还没有计时打卡。原有完成情况继续保留在学习进度中。</p>:<><div>{sorted.slice(0,showAll?undefined:5).map(s=><article className="clock-record" key={s.id}><div><strong>{niceTime(s.startedAt)} — {new Date(s.endedAt).toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit'})}</strong><p>任务 {s.date.slice(5)} · {durationText(s.durationMs)} {s.source==='manual'&&' · 手动补记'}{s.adjusted&&' · 已调整'}</p><p>{s.device||'设备未记录'} · IP 推测地区：{s.networkRegion||'未记录'}</p>{s.ip&&<p>公网 IP：{s.ip}</p>}{s.note&&<p className="clock-note">{s.note}</p>}</div><div className="clock-record-actions"><button disabled={busy} onClick={()=>edit(s)}>修改</button><button disabled={busy} onClick={()=>setConfirm(s.id)}>删除</button></div></article>)}</div>{sorted.length>5&&<button className="clock-text" onClick={()=>setShowAll(v=>!v)}>{showAll?'收起':'查看全部记录'}</button>}</>}{state?.sessions.some(s=>s.deleted&&s.date===date)&&<details className="clock-trash"><summary>已删除记录（可恢复）</summary>{state.sessions.filter(s=>s.deleted&&s.date===date).map(s=><div key={s.id}>{niceTime(s.startedAt)} · {durationText(s.durationMs)}<button disabled={busy} onClick={()=>act('restore',{id:s.id})}><RotateCcw size={13}/>恢复</button></div>)}</details>}</details><div className="task-checkin-footer"><button className="clock-text" disabled={busy} onClick={()=>onAdjust(date)}>顺延 / 调整状态</button></div><p className="clock-hint">确认打卡后自动完成任务，并显示累计学习时长。</p></div></DialogContent></Dialog>
 <Dialog open={!!mode} onOpenChange={v=>{if(!busy&&!v){setMode(null);setForm(null)}}}><DialogContent className="study-dialog clock-dialog"><DialogTitle>{mode==='save'?'确认本次打卡':mode==='edit'?'修改学习记录':'补记学习'}</DialogTitle><DialogDescription>按实际学习情况填写。时间均为北京时间，休息不计入有效学习时长。</DialogDescription>{form&&<><label>学习任务<select disabled={mode==='save'||busy} value={form.date} onChange={e=>setForm({...form,date:e.target.value})}>{days.map(d=><option key={d.date} value={d.date}>{d.date.slice(5)} · {d.subject}</option>)}</select></label><label>开始时间<input disabled={busy} type="datetime-local" step="1" value={form.startedAt} onChange={e=>setForm({...form,startedAt:e.target.value})}/></label><label>结束时间<input disabled={busy} type="datetime-local" step="1" value={form.endedAt} onChange={e=>setForm({...form,endedAt:e.target.value})}/></label><label>有效学习时长（分钟，扣除休息）<input disabled={busy} type="number" min="0.016" max="1440" step="any" value={form.minutes} onChange={e=>setForm({...form,minutes:e.target.value})}/></label><label>学了什么（选填）<textarea disabled={busy} maxLength={500} rows={3} placeholder="例如：做完数学例题，复习了逻辑错题。" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label>{error&&<p className="clock-error" role="alert">{error}</p>}<button className="clock-primary" disabled={busy} onClick={submit}>{busy?'正在保存…':mode==='edit'?'保存修改':'确认打卡'}</button>{mode==='save'&&<button disabled={busy} className="clock-text" onClick={async()=>{if(await act('resume',{id:form.id,version:form.version})){setMode(null);setForm(null)}}}>误点结束，继续计时</button>}<p className="clock-hint">{mode==='edit'?'修改记录不改变任务完成状态。':'确认后保存时长，并将这项任务标记为已完成。'}</p></>}</DialogContent></Dialog>
 <Dialog open={!!confirm} onOpenChange={v=>{if(!busy&&!v)setConfirm(null)}}><DialogContent className="study-dialog"><DialogTitle>{confirm==='cancel'?'取消本次计时？':'删除这条打卡？'}</DialogTitle><DialogDescription>{confirm==='cancel'?'本次不会计入时长，原有任务进度和历史打卡不会改变。':'累计时长会重新计算，删除后仍可以在记录底部恢复。任务完成状态不受影响。'}</DialogDescription>{error&&<p className="clock-error">{error}</p>}<button className="clock-primary" disabled={busy} onClick={async()=>{if(await act(confirm==='cancel'?'cancel':'delete',confirm==='cancel'?{}:{id:confirm})){setConfirm(null);setMessage('已处理，原有任务进度未改变。')}}}>确认{confirm==='cancel'?'取消':'删除'}</button><button disabled={busy} className="clock-text" onClick={()=>setConfirm(null)}>返回</button></DialogContent></Dialog>
 </section>
}
